set_property PACKAGE_PIN U18 [get_ports clk]
set_property PACKAGE_PIN G14 [get_ports led]
set_property PACKAGE_PIN J15 [get_ports rest_n]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports led]
set_property IOSTANDARD LVCMOS33 [get_ports rest_n]

set_property PACKAGE_PIN E18 [get_ports iic_scl]
set_property PACKAGE_PIN F17 [get_ports iic_sda]
set_property IOSTANDARD LVCMOS33 [get_ports iic_scl]
set_property IOSTANDARD LVCMOS33 [get_ports iic_sda]

set_property IOSTANDARD LVCMOS33 [get_ports uart_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_txd]
set_property PACKAGE_PIN J14 [get_ports uart_rxd]
set_property PACKAGE_PIN K18 [get_ports uart_txd]

set_property PACKAGE_PIN V20 [get_ports motor]
set_property PACKAGE_PIN Y19 [get_ports motor_2]
set_property PACKAGE_PIN Y18 [get_ports motor_3]
set_property PACKAGE_PIN W20 [get_ports motor_4]
set_property IOSTANDARD LVCMOS33 [get_ports motor]
set_property IOSTANDARD LVCMOS33 [get_ports motor_2]
set_property IOSTANDARD LVCMOS33 [get_ports motor_3]
set_property IOSTANDARD LVCMOS33 [get_ports motor_4]
